# Generated by Django 4.2 on 2023-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('passenger_count', models.IntegerField()),
            ],
        ),
    ]
